[package]
name = "leaderboard"
version = "0.1.1"
edition = "2021"
description = "Provides leaderboard functions for Vec such as ranking with ex aequos"
license = "Unlicense"
repository = "https://github.com/Inspirateur/leaderboard"
keywords = ["ranking", "rank", "ex-aequo", "standing", "vec"]
